name: my-environment
channels:
  #- omnia # outdated - we don't use omnia anymore
  - conda-forge
dependencies:
  - openmm >= 7.6
  - pdbfixer >= 1.5
  - mdtraj
  - pip
  - pip:
    - flake8
    - pytest
    - build
