name: my-environment
channels:
  - conda-forge
dependencies:
  - openmm >= 7.6
  - pdbfixer >= 1.5
  - mdtraj
  - openff-toolkit
  - openmmforcefields
  - pip
  - pip:
    - flake8
    - pytest
    - build
