import os
import re
import subprocess
from typing import Any, Dict, List, Optional, Union

from pydantic import ValidationError

from mdcrow.ldp_env.state import MDCrowState

from .pdb_fix import Validate_Fix_PDB
from .small_mol import MolPDB


def summarize_errors(errors):
    error_summary = {}

    # Regular expression pattern to capture the error type and line number
    pattern = r"\[!\] Offending field \((.+?)\) at line (\d+)"

    for error in errors:
        match = re.search(pattern, error)
        if match:
            error_type, line_number = match.groups()
            # If this error type hasn't been seen before,
            # initialize it in the dictionary
            if error_type not in error_summary:
                error_summary[error_type] = {"lines": []}
            error_summary[error_type]["lines"].append(line_number)

    # Format the summarized errors for display
    summarized_strings = []
    for error_type, data in error_summary.items():
        line_count = len(data["lines"])
        if line_count > 3:
            summarized_strings.append(f"{error_type}: total {line_count} lines")
        else:
            summarized_strings.append(f"{error_type}: lines: {','.join(data['lines'])}")

    return summarized_strings


class Molecule:
    def __init__(self, filename, file_id, number_of_molecules=1, instructions=None):
        self.filename = filename
        self.id = file_id
        self.number_of_molecules = number_of_molecules
        self.instructions = instructions if instructions else []
        self.load()

    def load(self):
        # Load the molecule data (optional)
        pass

    def get_number_of_atoms(self):
        # Return the number of atoms in this molecule
        pass


class PackmolBox:
    def __init__(
        self,
        path_registry,
        file_number=1,
        file_description="PDB file for simulation with: \n",
    ):
        self.path_registry = path_registry
        self.molecules = []
        self.file_number = file_number
        self.file_description = file_description
        self.final_name = None

    def add_molecule(self, molecule: Molecule) -> None:
        self.molecules.append(molecule)
        self.file_description += f"""{molecule.number_of_molecules} of
        {molecule.filename} as {molecule.instructions} \n"""
        return None

    def generate_input_header(self) -> None:
        # Generate the header of the input file in .inp format
        orig_pdbs_ids = [
            f"{molecule.number_of_molecules}_{molecule.id}"
            for molecule in self.molecules
        ]

        _final_name = f'{"_and_".join(orig_pdbs_ids)}'

        self.file_description = (
            "Packed Structures of the following molecules:\n"
            + "\n".join(
                [
                    f"Molecule ID: {molecule.id}, "
                    f"Number of Molecules: {molecule.number_of_molecules}"
                    for molecule in self.molecules
                ]
            )
        )
        while os.path.exists(
            f"{self.path_registry.ckpt_files}/pdb/{_final_name}_v{self.file_number}.pdb"
        ):
            self.file_number += 1

        self.final_name = f"{_final_name}_v{self.file_number}.pdb"
        with open("packmol.inp", "w") as out:
            out.write("## Automatically generated by LangChain\n")
            out.write("tolerance 2.0\n")
            out.write("filetype pdb\n")
            out.write(
                f"output {self.final_name}\n"
            )  # this is the name of the final file
            out.close()
        return None

    def generate_input(self) -> str:
        input_data = []
        for molecule in self.molecules:
            input_data.append(f"structure {molecule.filename}")
            input_data.append(f"  number {molecule.number_of_molecules}")
            for idx, instruction in enumerate(molecule.instructions):
                input_data.append(f"  {molecule.instructions[idx]}")
            input_data.append("end structure")

        # Convert list of input data to a single string
        return "\n".join(input_data)

    def run_packmol(self):
        validator = Validate_Fix_PDB()
        # Use the generated input to execute Packmol
        input_string = self.generate_input()
        # Write the input to a file
        with open("packmol.inp", "a") as f:
            f.write(input_string)
        # Here, run Packmol using the subprocess module or similar
        cmd = "packmol < packmol.inp"
        result = subprocess.run(cmd, shell=True, text=True, capture_output=True)
        if result.returncode != 0:
            print("Packmol failed to run using the command: 'packmol < packmol.inp'.")
            result = subprocess.run(
                "./" + cmd, shell=True, text=True, capture_output=True
            )
            if result.returncode != 0:
                raise RuntimeError(
                    "Packmol failed to run with './packmol < packmol.inp' "
                    "command. Please check the input file and try again."
                )

        # validate final pdb
        pdb_validation = validator.validate_pdb_format(f"{self.final_name}")
        if pdb_validation[0] == 0:
            # delete .inp files
            # os.remove("packmol.inp")
            for molecule in self.molecules:
                os.remove(molecule.filename)
            # name of packed pdb file
            time_stamp = self.path_registry.get_timestamp()[-6:]
            os.rename(
                self.final_name,
                f"{self.path_registry.ckpt_pdb}/{self.final_name}",
            )
            self.path_registry.map_path(
                f"PACKED_{time_stamp}",
                f"{self.path_registry.ckpt_pdb}/{self.final_name}",
                self.file_description,
            )
            # move file to files/pdb
            print("Successful!")
            return f"PDB file validated successfully. FileID: PACKED_{time_stamp}"
        elif pdb_validation[0] == 1:
            # format pdb_validation[1] list of errors
            errors = summarize_errors(pdb_validation[1])
            # delete .inp files

            # os.remove("packmol.inp")
            print("errors:", f"{errors}")
            return "PDB file not validated, errors found {}".format(("\n").join(errors))


def packmol_wrapper(
    path_registry,
    pdbfiles,
    files_id,
    number_of_molecules,
    instructions,
):
    """Useful when you need to create a box
    of different types of molecules molecules"""

    # create a box
    box = PackmolBox(path_registry)
    # add molecules to the box
    for (
        pdbfile,
        file_id,
        number_of_molecules,
        instructions,
    ) in zip(pdbfiles, files_id, number_of_molecules, instructions):
        molecule = Molecule(pdbfile, file_id, number_of_molecules, instructions)
        box.add_molecule(molecule)
    # generate input header
    box.generate_input_header()
    # generate input
    # run packmol
    print("Packing:", box.file_description, "\nThe file name is:", box.final_name)
    return box.run_packmol()


def _get_sm_pdbs(state, small_molecules):
    all_files = state.path_registry.list_path_names()
    for molecule in small_molecules:
        # check path registry for molecule.pdb
        if molecule not in all_files:
            # download molecule using small_molecule_pdb from MolPDB
            molpdb = MolPDB(state.path_registry)
            molpdb.small_molecule_pdb(molecule)
    print("Small molecules PDBs created successfully")


def validate_input(state, values: Union[str, Dict[str, Any]]) -> Dict:
    # check if is only a string
    if isinstance(values, str):
        print("values is a string", values)
        raise ValidationError("Input must be a dictionary")
    pdbfiles = values.get("pdbfile_ids", [])
    small_molecules = values.get("small_molecules", [])
    number_of_molecules = values.get("number_of_molecules", [])
    instructions = values.get("instructions", [])
    number_of_species = len(pdbfiles) + len(small_molecules)

    if not number_of_species == len(number_of_molecules):
        if not number_of_species == len(instructions):
            return {
                "error": (
                    "The length of number_of_molecules AND instructions "
                    "must be equal to the number of species in the system. "
                    f"You have {number_of_species} "
                    f"from {len(pdbfiles)} pdbfiles and {len(small_molecules)} "
                    "small molecules. You have included "
                    f"{len(number_of_molecules)} values for "
                    f"number_of_molecules and {len(instructions)}"
                    "instructions."
                ),
                **values,
            }
        return {
            "error": (
                "The length of number_of_molecules must be equal to the "
                f"number of species in the system. You have {number_of_species} "
                f"from {len(pdbfiles)} pdbfiles and {len(small_molecules)} "
                f"small molecules. You have included "
                f"{len(number_of_molecules)} values "
                "for number_of_molecules"
            ),
            **values,
        }
    elif not number_of_species == len(instructions):
        return {
            "error": (
                "The length of instructions must be equal to the "
                f"number of species in the system. You have {number_of_species} "
                f"from {len(pdbfiles)} pdbfiles and {len(small_molecules)} "
                "small molecules. You have included "
                f"{len(instructions)} instructions."
            ),
            **values,
        }
    registry = state.path_registry
    molPDB = MolPDB(registry)
    for instruction in instructions:
        if len(instruction) != 1:
            return {
                "error": (
                    "Each instruction must be a single string. "
                    "If necessary, use newlines in a instruction string."
                ),
                **values,
            }
        # TODO enhance this validation with more packmol instructions
        first_word = instruction[0].split(" ")[0]
        if first_word == "center":
            if len(instruction[0].split(" ")) == 1:
                return {
                    "error": (
                        "The instruction 'center' must be "
                        "accompanied by more instructions. "
                        "Example 'fixed 0. 0. 0. 0. 0. 0.' "
                        "The complete instruction would be: 'center \n fixed 0. 0. "
                        "0. 0. 0. 0.' with a newline separating the two "
                        "instructions."
                    ),
                    **values,
                }
        elif first_word not in [
            "inside",
            "outside",
            "fixed",
        ]:
            return {
                "error": (
                    "The first word of each instruction must be one of "
                    "'inside' or 'outside' or 'fixed' \n"
                    "examples: center \n fixed 0. 0. 0. 0. 0. 0.,\n"
                    "inside box -10. 0. 0. 10. 10. 10. \n"
                ),
                **values,
            }

    # Further validation, e.g., checking if files exist
    file_ids = registry.list_path_names()

    for pdbfile_id in pdbfiles:
        if "_" not in pdbfile_id:
            return {
                "error": (
                    f"{pdbfile_id} is not a valid pdbfile_id in the path_registry"
                ),
                **values,
            }
        if pdbfile_id not in file_ids:
            # look for files in the current directory
            # that match some part of the pdbfile
            ids_w_description = registry.list_path_names_and_descriptions()

            return {
                "error": (
                    f"PDB file ID {pdbfile_id} does not exist "
                    "in the path registry.\n"
                    f"This are the files IDs: {ids_w_description} "
                ),
                **values,
            }
        for small_molecule in small_molecules:
            if small_molecule not in file_ids:
                result = molPDB.small_molecule_pdb(small_molecule)
                if "successfully" not in result:
                    return {
                        "error": (
                            f"{small_molecule} could not be converted to a pdb "
                            "file. Try with a different name, or with the SMILES "
                            "of the small molecule"
                        ),
                        **values,
                    }
    return values


def get_values(values):
    return (
        values.get("pdbfile_ids", []),
        values.get("small_molecules", []),
        values.get("number_of_molecules", []),
        values.get("instructions", []),
        values.get("error", None),
    )


def pack_molecules(
    state: MDCrowState,
    pdbfile_ids: Optional[List[str]],
    small_molecules: Optional[List[str]],
    number_of_molecules: Optional[List[int]],
    instructions: Optional[List[List[str]]],
):
    """
    Description:
        Useful when you need to create a box of different types of chemical species.
        Three different examples:
        pdbfile_ids: ['1a2b_123456']
        small_molecules: ['water']
        number_of_molecules: [1, 1000]
        instructions: [
        ['fixed 0. 0. 0. 0. 0. 0.'
          centerofmass'],
        ['inside box 0. 0. 0. 90. 90. 90.']
        ]
        will pack 1 molecule of 1a2b_123456 at the origin
        and 1000 molecules of water.
        pdbfiles_id: ['1a2b_123456']
        number_of_molecules: [1]
        instructions: [['fixed  0. 0. 0. 0. 0. 0.'
          center]]
        This will fix the barocenter of protein 1a2b_123456 at
        the center of the box with no rotation.
        pdbfiles_id: ['1a2b_123456']
        number_of_molecules: [1]
        instructions: [['outside sphere 2.30 3.40 4.50 8.0]]
        This will place the protein 1a2b_123456 outside a sphere
        centered at 2.30 3.40 4.50 with radius 8.0

    Args:
        state (MDCrowState): The current state of the MDCrow environment.
        pdbfile_ids (Optional[List[str]]): List of PDB file IDs (from path registry) \
            to be packed into the box.
        small_molecules (Optional[List[str]], optional): List of small molecules to \
            include in the system.
            Examples: "water", "benzene", "toluene". Defaults to an empty list.
        number_of_molecules (Optional[List[int]]): List indicating the number of \
            instances of each species
            (proteins or small molecules) to be packed into the box. Each number \
                corresponds to a species.
        instructions (Optional[List[List[str]]]): List of packing instructions for \
            each species.
            - Each molecule has an associated list of instructions.
            - Each instruction should be a string, for example:
              `"inside box 0. 0. 0. 90. 90. 90."`
    """

    values = {
        "pdbfile_ids": pdbfile_ids,
        "small_molecules": small_molecules,
        "number_of_molecules": number_of_molecules,
        "instructions": instructions,
    }
    if state.path_registry is None:  # this should not happen
        raise ValidationError("Path registry not initialized")
    try:
        values = validate_input(state, values)
    except ValidationError as e:
        return f"Failed. ValidationError: {e}"
    (
        pdbfile_ids,
        small_molecules,
        number_of_molecules,
        instructions,
        error_msg,
    ) = get_values(values)
    if error_msg:
        print("Error in Packmol inputs:", error_msg)
        return f"Failed. Error in inputs: {error_msg}", 0, False
    print("Starting Packmol Tool!")
    # pdbfile_ids = values["pdbfile_ids"] or []

    # number_of_molecules = values.get("number_of_molecules", []) or []
    # instructions = values.get("instructions", []) or []
    # small_molecules = values.get("small_molecules", []) or []
    if not isinstance(pdbfile_ids, list) or any(
        not isinstance(i, str) for i in pdbfile_ids
    ):
        raise TypeError("pdbfile_ids must be a list of strings")

    if not isinstance(number_of_molecules, list) or any(
        not isinstance(i, int) for i in number_of_molecules
    ):
        raise TypeError("number_of_molecules must be a list of integers")

    if not isinstance(instructions, list) or any(
        not isinstance(i, list) or any(not isinstance(j, str) for j in i)
        for i in instructions
    ):
        raise TypeError("instructions must be a list of lists of strings")

    if not isinstance(small_molecules, list) or any(
        not isinstance(i, str) for i in small_molecules
    ):
        raise TypeError("small_molecules must be a list of strings")
    # make sure small molecules are all downloaded
    pdbfiles = [
        state.path_registry.get_mapped_path(pdbfile) for pdbfile in (pdbfile_ids or [])
    ]
    pdbfile_names = [pdbfile.split("/")[-1] for pdbfile in pdbfiles]
    # copy them to the current directory with temp_ names

    pdbfile_names = [
        f"{state.path_registry.ckpt_files}/temp_{pdbfile_name}"
        for pdbfile_name in pdbfile_names
    ]
    _get_sm_pdbs(state, small_molecules)
    small_molecules_files = [
        state.path_registry.get_mapped_path(sm) for sm in (small_molecules or [])
    ]
    small_molecules_file_names = [
        small_molecule.split("/")[-1] for small_molecule in small_molecules_files
    ]
    small_molecules_file_names = [
        f"{state.path_registry.ckpt_files}/temp_{small_molecule_file_name}"
        for small_molecule_file_name in small_molecules_file_names
    ]
    # append small molecules to pdbfiles
    if pdbfiles is not None:
        pdbfiles.extend(small_molecules_files)
    if pdbfile_names is not None:
        pdbfile_names.extend(small_molecules_file_names)
    if pdbfile_ids is not None:
        pdbfile_ids.extend(small_molecules or [])

    for pdbfile, pdbfile_name in zip(pdbfiles, pdbfile_names):
        os.system(f"cp {pdbfile} {pdbfile_name}")
    # check if packmol is installed
    cmd = "command -v packmol"
    result = subprocess.run(cmd, shell=True, text=True, capture_output=True)
    if result.returncode != 0:
        result = subprocess.run("./" + cmd, shell=True, text=True, capture_output=True)
        if result.returncode != 0:
            return (
                (
                    "Failed. Packmol is not installed. Please install"
                    "Packmol from "
                    "'https://m3g.github.io/packmol/download.shtml'"
                    "and try again."
                ),
                0,
                False,
            )

    try:
        return (
            "Succeeded. "
            + packmol_wrapper(
                state.path_registry,
                pdbfiles=pdbfile_names,
                files_id=pdbfile_ids,
                number_of_molecules=number_of_molecules,
                instructions=instructions,
            ),
            0,
            False,
        )
    except RuntimeError as e:
        return f"Failed. Packmol failed to run with error: {e}", 0, False
