name: test

on:
  push:
    branches:
      - '*'


jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]
      max-parallel: 1

    steps:
    - uses: actions/checkout@v2
    - name: Set up conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: my-environment
        environment-file: environment.yaml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: true
    - name: Install [openmm pdbfixer] with conda
      shell: bash -l {0}
      run: |
        conda install -c conda-forge openmm pdbfixer
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
    - name: Install
      shell: bash -l {0}
      run: |
        pip install .
    - name: Check pre-commit
      run: |
        pip install pre-commit
        pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
    - name: Run Test
      shell: bash -l {0}
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SEMANTIC_SCHOLAR_API_KEY: ${{ secrets.SEMANTIC_SCHOLAR_API_KEY }}
        PQA_API_KEY : ${{ secrets.PQA_API_TOKEN }}
      run: |
         pytest -m "not skip" tests
